version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodmatch
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  

  app:
    build: .
    container_name: foodmatch
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Removed unnecessary '='
      - DB_USER=root  # Removed unnecessary '='
      - DB_PASSWORD=password  # Removed unnecessary '='
      - DB_NAME=foodmatch  # Removed unnecessary '='
    ports:
      - "5000:5000"

volumes:
  mysql_data: